baseURL = "https://KasiaOtko.github.io/"
languageCode = "en-us"
title = "Social Data Analysis Final Project"
theme = "introduction"
pluralizelisttitles = "false"
[markup.goldmark.renderer]
    unsafe = true

 [[menu.main]]
     name    = "Home"
     url     = "/"
     weight = 1

 [[menu.main]]
     identifier = "BokehPlots"
     name    = "Bokeh Plots"
     url     = "/bokehplots/"
     weight = 2

# [[menu.main]]
#    name    = "Section2"
#     url     = "/section2/"
#     weight  = 1



#[params]
#	themeStyle                   = "auto"	# Choose "light" or "dark" or "auto"

	# Configure the home page
    	[params.home]
#       	introHeight              = "medium"            # Input either "medium" or "large" or "fullheight"
#		showAllPosts             = false	       # Set true to list all posts on home page, or set false to link to separate blog list page
		allPostsArchiveFormat    = false# show all posts in an archive format
